# Generated by Django 3.2.16 on 2023-05-26 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=102)),
                ('subject', models.CharField(max_length=102)),
                ('message', models.TextField(blank=True)),
                ('budget', models.CharField(blank=True, max_length=102)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
